% James Jarman (j.jarman-20@lboro.ac.uk)
% Loughborough University
% 2024

clear; close all;

%% Q3gl functions phi_i(x,y) N=16

% Basis functions expressed as:
% phi(xi,yi) = c1*xi^3*yi^3 + c2*xi^3*yi^2 + c3*x^2*yi^3 + ...
%              c4*xi^3*yi + c5*xi*yi^3 + c6*xi^2*yi^2 + c7*xi^3 + ...
%              c8*xi^2*yi + c9*xi*yi^2 + c10*yi^3 + c11*xi^2 + ...
%              c12*xi*yi + c13*yi^2 + c14*xi + c15*yi + c16
% Numbering of the nodes:
%  1 (  -1,-1)
%  2 (   1,-1)
%  3 (   1, 1)
%  4 (  -1, 1)
%  5 (-1/sqrt(5),-1)
%  6 ( 1/sqrt(5),-1)
%  7 (   1,-1/sqrt(5))
%  8 (   1, 1/sqrt(5))
%  9 ( 1/sqrt(5), 1)
% 10 (-1/sqrt(5), 1)
% 11 (  -1, 1/sqrt(5))
% 12 (  -1,-1/sqrt(5))
% 13 (-1/sqrt(5),-1/sqrt(5))
% 14 ( 1/sqrt(5),-1/sqrt(5))
% 15 ( 1/sqrt(5), 1/sqrt(5))
% 16 (-1/sqrt(5), 1/sqrt(5))

isqrt5 = sym(1/sqrt(5)); % create symbolic variable for 1/sqrt(5)

xi = [-1  1  1 -1 -isqrt5 isqrt5 1 1 isqrt5 -isqrt5 -1 -1 -isqrt5 ...
    isqrt5 isqrt5 -isqrt5];
yi = [-1 -1  1 1 -1 -1 -isqrt5 isqrt5 1 1 isqrt5 -isqrt5 -isqrt5 ...
    -isqrt5 isqrt5 isqrt5];

A = sym(zeros(16,16));

for i = 1:16
    A(i,:) = [xi(i)^3*yi(i)^3, ...
              xi(i)^3*yi(i)^2, ...
              xi(i)^2*yi(i)^3, ...
              xi(i)^3*yi(i),   ...
              xi(i)*yi(i)^3, ...
              xi(i)^2*yi(i)^2, ...
              xi(i)^3, ...
              xi(i)^2*yi(i), ...
              xi(i)*yi(i)^2, ...
              yi(i)^3, ...
              xi(i)^2, ...
              xi(i)*yi(i), ...
              yi(i)^2, ...
              xi(i), ...
              yi(i), ...
              1];
end

b = sym(eye(16,16));
  
% Coefficients of the basis functions
c = linsolve(A,b);


syms x y

phi = sym(zeros(16,1)); % expression of the basis function phi

dphidx = sym(zeros(16,1));
dphidy = sym(zeros(16,1));
for j = 1:16
    phi(j,1) = c(1,j)*x^3*y^3 + ...
               c(2,j)*x^3*y^2 + ...
               c(3,j)*x^2*y^3 + ...
               c(4,j)*x^3*y + ...
               c(5,j)*x*y^3 + ...
               c(6,j)*x^2*y^2 + ...
               c(7,j)*x^3 + ...
               c(8,j)*x^2*y + ...
               c(9,j)*x*y^2 + ...
               c(10,j)*y^3 + ...
               c(11,j)*x^2 + ...
               c(12,j)*x*y + ...
               c(13,j)*y^2 + ...
               c(14,j)*x + ...
               c(15,j)*y + ...
               c(16,j);
    dphidx(j,1) = diff(phi(j,1),x);
    dphidy(j,1) = diff(phi(j,1),y);
end

%% Q3gl functions psi_j(x,y) M=16

% Basis functions expressed as:
% psi(xi,yi) = c1*xi^3*yi^3 + c2*xi^3*yi^2 + c3*x^2*yi^3 + ...
%              c4*xi^3*yi + c5*xi*yi^3 + c6*xi^2*yi^2 + c7*xi^3 + ...
%              c8*xi^2*yi + c9*xi*yi^2 + c10*yi^3 + c11*xi^2 + ...
%              c12*xi*yi + c13*yi^2 + c14*xi + c15*yi + c16
% Numbering of the nodes:
%  1 (  -1,-1)
%  2 (   1,-1)
%  3 (   1, 1)
%  4 (  -1, 1)
%  5 (-1/sqrt(5),-1)
%  6 ( 1/sqrt(5),-1)
%  7 (   1,-1/sqrt(5))
%  8 (   1, 1/sqrt(5))
%  9 ( 1/sqrt(5), 1)
% 10 (-1/sqrt(5), 1)
% 11 (  -1, 1/sqrt(5))
% 12 (  -1,-1/sqrt(5))
% 13 (-1/sqrt(5),-1/sqrt(5))
% 14 ( 1/sqrt(5),-1/sqrt(5))
% 15 ( 1/sqrt(5), 1/sqrt(5))
% 16 (-1/sqrt(5), 1/sqrt(5))

isqrt5 = sym(1/sqrt(5)); % create symbolic variable for 1/sqrt(5)

xi = [-1  1  1 -1 -isqrt5 isqrt5 1 1 isqrt5 -isqrt5 -1 -1 -isqrt5 ...
    isqrt5 isqrt5 -isqrt5];
yi = [-1 -1  1 1 -1 -1 -isqrt5 isqrt5 1 1 isqrt5 -isqrt5 -isqrt5 ...
    -isqrt5 isqrt5 isqrt5];

A = sym(zeros(16,16));

for i = 1:16
    A(i,:) = [xi(i)^3*yi(i)^3, ...
              xi(i)^3*yi(i)^2, ...
              xi(i)^2*yi(i)^3, ...
              xi(i)^3*yi(i),   ...
              xi(i)*yi(i)^3, ...
              xi(i)^2*yi(i)^2, ...
              xi(i)^3, ...
              xi(i)^2*yi(i), ...
              xi(i)*yi(i)^2, ...
              yi(i)^3, ...
              xi(i)^2, ...
              xi(i)*yi(i), ...
              yi(i)^2, ...
              xi(i), ...
              yi(i), ...
              1];
end

b = sym(eye(16,16));
  
% Coefficients of the basis functions
c = linsolve(A,b);


syms x y

psi = sym(zeros(16,1)); % expression of the basis function psi

dpsidx = sym(zeros(16,1));
dpsidy = sym(zeros(16,1));
for j = 1:16
    psi(j,1) = c(1,j)*x^3*y^3 + ...
               c(2,j)*x^3*y^2 + ...
               c(3,j)*x^2*y^3 + ...
               c(4,j)*x^3*y + ...
               c(5,j)*x*y^3 + ...
               c(6,j)*x^2*y^2 + ...
               c(7,j)*x^3 + ...
               c(8,j)*x^2*y + ...
               c(9,j)*x*y^2 + ...
               c(10,j)*y^3 + ...
               c(11,j)*x^2 + ...
               c(12,j)*x*y + ...
               c(13,j)*y^2 + ...
               c(14,j)*x + ...
               c(15,j)*y + ...
               c(16,j);
    dpsidx(j,1) = diff(psi(j,1),x);
    dpsidy(j,1) = diff(psi(j,1),y);
end

%% 

mat0X = sym(zeros(16,16));
mat0Y = sym(zeros(16,16));
matX0 = sym(zeros(16,16));
matY0 = sym(zeros(16,16));

for i = 1:16
    for j = 1:16
        mat0X(i,j) = int(int(phi(i,1)*dpsidx(j,1),x,-1,1),y,-1,1);
        mat0Y(i,j) = int(int(phi(i,1)*dpsidy(j,1),x,-1,1),y,-1,1);
        matX0(i,j) = int(int(dphidx(i,1)*psi(j,1),x,-1,1),y,-1,1);
        matY0(i,j) = int(int(dphidy(i,1)*psi(j,1),x,-1,1),y,-1,1);
    end
end
