% James Jarman (j.jarman-20@lboro.ac.uk)
% Loughborough University
% 2024

clear; close all;

%%

% Basis functions expressed as:
% chi(xi,yi) = c1*xi^3*yi^3 + c2*xi^3*yi^2 + c3*x^2*yi^3 + ...
%              c4*xi^3*yi + c5*xi*yi^3 + c6*xi^2*yi^2 + c7*xi^3 + ...
%              c8*xi^2*yi + c9*xi*yi^2 + c10*yi^3 + c11*xi^2 + ...
%              c12*xi*yi + c13*yi^2 + c14*xi + c15*yi + c16
% Numbering of the nodes:
%  1 (  -1,-1)
%  2 (   1,-1)
%  3 (   1, 1)
%  4 (  -1, 1)
%  5 (-1/3,-1)
%  6 ( 1/3,-1)
%  7 (   1,-1/3)
%  8 (   1, 1/3)
%  9 ( 1/3, 1)
% 10 (-1/3, 1)
% 11 (  -1, 1/3)
% 12 (  -1,-1/3)
% 13 (-1/3,-1/3)
% 14 ( 1/3,-1/3)
% 15 ( 1/3, 1/3)
% 16 (-1/3, 1/3)

third = sym(1/3); % create symbolic variable for 1/3

xi = [-1  1  1 -1 -third third 1 1 third -third -1 -1 -third third ...
    third -third];
yi = [-1 -1  1 1 -1 -1 -third third 1 1 third -third -third -third ...
    third third];

A = sym(zeros(16,16));

for i = 1:16
    A(i,:) = [xi(i)^3*yi(i)^3, ...
              xi(i)^3*yi(i)^2, ...
              xi(i)^2*yi(i)^3, ...
              xi(i)^3*yi(i),   ...
              xi(i)*yi(i)^3, ...
              xi(i)^2*yi(i)^2, ...
              xi(i)^3, ...
              xi(i)^2*yi(i), ...
              xi(i)*yi(i)^2, ...
              yi(i)^3, ...
              xi(i)^2, ...
              xi(i)*yi(i), ...
              yi(i)^2, ...
              xi(i), ...
              yi(i), ...
              1];
end

b = sym(eye(16,16));
  
% Coefficients of the basis functions
c = linsolve(A,b);


syms x y

chi = sym(zeros(16,1)); % expression of the basis function chi

dchidx = sym(zeros(16,1));
dchidy = sym(zeros(16,1));
for j = 1:16
    chi(j,1) = c(1,j)*x^3*y^3 + ...
               c(2,j)*x^3*y^2 + ...
               c(3,j)*x^2*y^3 + ...
               c(4,j)*x^3*y + ...
               c(5,j)*x*y^3 + ...
               c(6,j)*x^2*y^2 + ...
               c(7,j)*x^3 + ...
               c(8,j)*x^2*y + ...
               c(9,j)*x*y^2 + ...
               c(10,j)*y^3 + ...
               c(11,j)*x^2 + ...
               c(12,j)*x*y + ...
               c(13,j)*y^2 + ...
               c(14,j)*x + ...
               c(15,j)*y + ...
               c(16,j);
    dchidx(j,1) = diff(chi(j,1),x);
    dchidy(j,1) = diff(chi(j,1),y);
end


symDERXX = sym(zeros(16,16));
symDERYY = sym(zeros(16,16));
symDERXY = sym(zeros(16,16));
symMASS  = sym(zeros(16,16));

for i = 1:16
    for j = 1:16
        symDERXX(i,j) = int(int(dchidx(i,1)*dchidx(j,1),x,-1,1),y,-1,1);
        symDERYY(i,j) = int(int(dchidy(i,1)*dchidy(j,1),x,-1,1),y,-1,1);
        symDERXY(i,j) = int(int(dchidx(i,1)*dchidy(j,1),x,-1,1),y,-1,1);
        symMASS(i,j)  = int(int(chi(i,1)*chi(j,1),x,-1,1),y,-1,1);
    end
end
